esphome:
  name: esphome-web-45c8cc
  friendly_name: Watering System
  min_version: 2025.11.0
  name_add_mac_suffix: false

esp32:
  variant: esp32
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Time component for timestamps
time:
  - platform: homeassistant
    id: homeassistant_time

# Hidden relay control switch
switch:
  - platform: gpio
    pin: 
      number: GPIO23
    id: water_pump_relay
    internal: true  # Hides from Home Assistant UI

# Manual watering button
button:
  - platform: template
    name: "Water Plant"
    id: water_plant_button
    icon: mdi:water
    on_press:
      - logger.log: "Manual watering started..."
      - switch.turn_on: water_pump_relay
      - delay: 3s
      - switch.turn_off: water_pump_relay
      - text_sensor.template.publish:
          id: last_watering_time
          state: !lambda |-
            char buf[64];
            time_t now = id(homeassistant_time).now().timestamp;
            strftime(buf, sizeof(buf), "%Y-%m-%d %H:%M:%S", localtime(&now));
            return {buf};
      - logger.log: "Manual watering complete"

# Last watering timestamp
text_sensor:
  - platform: template
    name: "Last Watering Time"
    id: last_watering_time
    icon: mdi:water-clock

sensor:
  # Temperature / Humidity sensor: DHT11
  - platform: dht
    pin: GPIO15
    model: DHT11
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 10s

  # HW-080 Soil Moisture
  - platform: adc
    pin: GPIO34
    name: "Soil Moisture"
    id: soil_moisture
    update_interval: 10s
    attenuation: 11db
    filters:
      - calibrate_linear:
          - 2.8 -> 0.0   # Dry (adjust after testing)
          - 1.2 -> 100.0 # Wet (adjust after testing)
      - lambda: return max(0.0f, min(100.0f, x));
    unit_of_measurement: "%"
    accuracy_decimals: 0

# Automatic watering when soil is dry
interval:
  - interval: 4d  # Check every 4 days
    then:
      - if:
          condition:
            lambda: 'return id(soil_moisture).state < 50.0;'  # Water if below 50%
          then:
            - logger.log: "Soil is dry, watering plant"
            - switch.turn_on: water_pump_relay
            - delay: 3s
            - switch.turn_off: water_pump_relay
            - text_sensor.template.publish:
                id: last_watering_time
                state: !lambda |-
                  char buf[64];
                  time_t now = id(homeassistant_time).now().timestamp;
                  strftime(buf, sizeof(buf), "%Y-%m-%d %H:%M:%S", localtime(&now));
                  return {buf};
            - logger.log: "Watering complete"